version=2
asset_format=video_side_by_side
fps=30
width=1920
height=1080
global_opacity=1.0
background_opacity=0.38
clip1_name=neko1
clip1_video=neko1.webm
clip1_frames=329
clip1_loop=false
clip1_frame_width=1920
clip1_frame_height=1080
clip1_offset_x=0
clip1_offset_y=0
clip2_name=neko2
clip2_video=neko2.webm
clip2_frames=239
clip2_loop=true
clip2_frame_width=1920
clip2_frame_height=1080
clip2_offset_x=0
clip2_offset_y=0
